from netaddr import IPAddress

p4 = bfrt.pontus_1_ROW.pipe


# This script configures QSFP ports automatically on the TOFINO Switch
# Adapted from ICA-1131 Intel Connectivity Academy Course
for qsfp_cage in [1, 5]:
    for lane in range(0, 1):
        dp = bfrt.port.port_hdl_info.get(CONN_ID = qsfp_cage, CHNL_ID = lane, print_ents = False).data[b'$DEV_PORT']
        bfrt.port.port.add(DEV_PORT= dp, SPEED = "BF_SPEED_100G", FEC = "BF_FEC_TYP_NONE", AUTO_NEGOTIATION = "PM_AN_FORCE_DISABLE", PORT_ENABLE = True)


def clear_all(verbose=True, batching=True):
    global p4
    global bfrt
    for table_types in (['MATCH_DIRECT', 'MATCH_INDIRECT_SELECTOR'],
                        ['SELECTOR'],
                        ['ACTION_PROFILE']):
        for table in p4.info(return_info=True, print_info=False):
            if table['type'] in table_types:
                if verbose:
                    print("Clearing table {:<40} ... ".
                          format(table['full_name']), end='', flush=True)
                table['node'].clear(batch=batching)
                if verbose:
                    print('Done')

clear_all(verbose=True)

division_table = p4.Ingress.division_table
division_table.add_with_set_division_action(divided_value=1, f_action=256)
division_table.add_with_set_division_action(divided_value=2, f_action=128)
division_table.add_with_set_division_action(divided_value=3, f_action=85)
division_table.add_with_set_division_action(divided_value=4, f_action=64)
division_table.add_with_set_division_action(divided_value=5, f_action=51)
division_table.add_with_set_division_action(divided_value=6, f_action=42)
division_table.add_with_set_division_action(divided_value=7, f_action=36)
division_table.add_with_set_division_action(divided_value=8, f_action=32)
division_table.add_with_set_division_action(divided_value=9, f_action=28)
division_table.add_with_set_division_action(divided_value=10, f_action=25)
division_table.add_with_set_division_action(divided_value=11, f_action=23)
division_table.add_with_set_division_action(divided_value=12, f_action=21)
division_table.add_with_set_division_action(divided_value=13, f_action=19)
division_table.add_with_set_division_action(divided_value=14, f_action=18)
division_table.add_with_set_division_action(divided_value=15, f_action=17)
division_table.add_with_set_division_action(divided_value=16, f_action=16)
division_table.add_with_set_division_action(divided_value=17, f_action=15)
division_table.add_with_set_division_action(divided_value=18, f_action=14)
division_table.add_with_set_division_action(divided_value=19, f_action=13)
division_table.add_with_set_division_action(divided_value=20, f_action=12)
division_table.add_with_set_division_action(divided_value=21, f_action=12)
division_table.add_with_set_division_action(divided_value=22, f_action=11)
division_table.add_with_set_division_action(divided_value=23, f_action=11)
division_table.add_with_set_division_action(divided_value=24, f_action=10)
division_table.add_with_set_division_action(divided_value=25, f_action=10)
division_table.add_with_set_division_action(divided_value=26, f_action=9)
division_table.add_with_set_division_action(divided_value=27, f_action=9)
division_table.add_with_set_division_action(divided_value=28, f_action=9)
division_table.add_with_set_division_action(divided_value=29, f_action=8)
division_table.add_with_set_division_action(divided_value=30, f_action=8)
division_table.add_with_set_division_action(divided_value=31, f_action=8)
division_table.add_with_set_division_action(divided_value=32, f_action=8)
division_table.add_with_set_division_action(divided_value=33, f_action=7)
division_table.add_with_set_division_action(divided_value=34, f_action=7)
division_table.add_with_set_division_action(divided_value=35, f_action=7)
division_table.add_with_set_division_action(divided_value=36, f_action=7)
division_table.add_with_set_division_action(divided_value=37, f_action=6)
division_table.add_with_set_division_action(divided_value=38, f_action=6)
division_table.add_with_set_division_action(divided_value=39, f_action=6)
division_table.add_with_set_division_action(divided_value=40, f_action=6)
division_table.add_with_set_division_action(divided_value=41, f_action=6)
division_table.add_with_set_division_action(divided_value=42, f_action=6)
division_table.add_with_set_division_action(divided_value=43, f_action=5)
division_table.add_with_set_division_action(divided_value=44, f_action=5)
division_table.add_with_set_division_action(divided_value=45, f_action=5)
division_table.add_with_set_division_action(divided_value=46, f_action=5)
division_table.add_with_set_division_action(divided_value=47, f_action=5)
division_table.add_with_set_division_action(divided_value=48, f_action=5)
division_table.add_with_set_division_action(divided_value=49, f_action=5)
division_table.add_with_set_division_action(divided_value=50, f_action=5)
division_table.add_with_set_division_action(divided_value=51, f_action=5)
division_table.add_with_set_division_action(divided_value=52, f_action=4)
division_table.add_with_set_division_action(divided_value=53, f_action=4)
division_table.add_with_set_division_action(divided_value=54, f_action=4)
division_table.add_with_set_division_action(divided_value=55, f_action=4)
division_table.add_with_set_division_action(divided_value=56, f_action=4)
division_table.add_with_set_division_action(divided_value=57, f_action=4)
division_table.add_with_set_division_action(divided_value=58, f_action=4)
division_table.add_with_set_division_action(divided_value=59, f_action=4)
division_table.add_with_set_division_action(divided_value=60, f_action=4)
division_table.add_with_set_division_action(divided_value=61, f_action=4)
division_table.add_with_set_division_action(divided_value=62, f_action=4)
division_table.add_with_set_division_action(divided_value=63, f_action=4)
division_table.add_with_set_division_action(divided_value=64, f_action=4)
division_table.add_with_set_division_action(divided_value=65, f_action=3)
division_table.add_with_set_division_action(divided_value=66, f_action=3)
division_table.add_with_set_division_action(divided_value=67, f_action=3)
division_table.add_with_set_division_action(divided_value=68, f_action=3)
division_table.add_with_set_division_action(divided_value=69, f_action=3)
division_table.add_with_set_division_action(divided_value=70, f_action=3)
division_table.add_with_set_division_action(divided_value=71, f_action=3)
division_table.add_with_set_division_action(divided_value=72, f_action=3)
division_table.add_with_set_division_action(divided_value=73, f_action=3)
division_table.add_with_set_division_action(divided_value=74, f_action=3)
division_table.add_with_set_division_action(divided_value=75, f_action=3)
division_table.add_with_set_division_action(divided_value=76, f_action=3)
division_table.add_with_set_division_action(divided_value=77, f_action=3)
division_table.add_with_set_division_action(divided_value=78, f_action=3)
division_table.add_with_set_division_action(divided_value=79, f_action=3)
division_table.add_with_set_division_action(divided_value=80, f_action=3)
division_table.add_with_set_division_action(divided_value=81, f_action=3)
division_table.add_with_set_division_action(divided_value=82, f_action=3)
division_table.add_with_set_division_action(divided_value=83, f_action=3)
division_table.add_with_set_division_action(divided_value=84, f_action=3)
division_table.add_with_set_division_action(divided_value=85, f_action=3)
division_table.add_with_set_division_action(divided_value=86, f_action=2)
division_table.add_with_set_division_action(divided_value=87, f_action=2)
division_table.add_with_set_division_action(divided_value=88, f_action=2)
division_table.add_with_set_division_action(divided_value=89, f_action=2)
division_table.add_with_set_division_action(divided_value=90, f_action=2)
division_table.add_with_set_division_action(divided_value=91, f_action=2)
division_table.add_with_set_division_action(divided_value=92, f_action=2)
division_table.add_with_set_division_action(divided_value=93, f_action=2)
division_table.add_with_set_division_action(divided_value=94, f_action=2)
division_table.add_with_set_division_action(divided_value=95, f_action=2)
division_table.add_with_set_division_action(divided_value=96, f_action=2)
division_table.add_with_set_division_action(divided_value=97, f_action=2)
division_table.add_with_set_division_action(divided_value=98, f_action=2)
division_table.add_with_set_division_action(divided_value=99, f_action=2)
division_table.add_with_set_division_action(divided_value=100, f_action=2)
division_table.add_with_set_division_action(divided_value=101, f_action=2)
division_table.add_with_set_division_action(divided_value=102, f_action=2)
division_table.add_with_set_division_action(divided_value=103, f_action=2)
division_table.add_with_set_division_action(divided_value=104, f_action=2)
division_table.add_with_set_division_action(divided_value=105, f_action=2)
division_table.add_with_set_division_action(divided_value=106, f_action=2)
division_table.add_with_set_division_action(divided_value=107, f_action=2)
division_table.add_with_set_division_action(divided_value=108, f_action=2)
division_table.add_with_set_division_action(divided_value=109, f_action=2)
division_table.add_with_set_division_action(divided_value=110, f_action=2)
division_table.add_with_set_division_action(divided_value=111, f_action=2)
division_table.add_with_set_division_action(divided_value=112, f_action=2)
division_table.add_with_set_division_action(divided_value=113, f_action=2)
division_table.add_with_set_division_action(divided_value=114, f_action=2)
division_table.add_with_set_division_action(divided_value=115, f_action=2)
division_table.add_with_set_division_action(divided_value=116, f_action=2)
division_table.add_with_set_division_action(divided_value=117, f_action=2)
division_table.add_with_set_division_action(divided_value=118, f_action=2)
division_table.add_with_set_division_action(divided_value=119, f_action=2)
division_table.add_with_set_division_action(divided_value=120, f_action=2)
division_table.add_with_set_division_action(divided_value=121, f_action=2)
division_table.add_with_set_division_action(divided_value=122, f_action=2)
division_table.add_with_set_division_action(divided_value=123, f_action=2)
division_table.add_with_set_division_action(divided_value=124, f_action=2)
division_table.add_with_set_division_action(divided_value=125, f_action=2)
division_table.add_with_set_division_action(divided_value=126, f_action=2)
division_table.add_with_set_division_action(divided_value=127, f_action=2)
division_table.add_with_set_division_action(divided_value=128, f_action=2)
division_table.add_with_set_division_action(divided_value=129, f_action=1)
division_table.add_with_set_division_action(divided_value=130, f_action=1)
division_table.add_with_set_division_action(divided_value=131, f_action=1)
division_table.add_with_set_division_action(divided_value=132, f_action=1)
division_table.add_with_set_division_action(divided_value=133, f_action=1)
division_table.add_with_set_division_action(divided_value=134, f_action=1)
division_table.add_with_set_division_action(divided_value=135, f_action=1)
division_table.add_with_set_division_action(divided_value=136, f_action=1)
division_table.add_with_set_division_action(divided_value=137, f_action=1)
division_table.add_with_set_division_action(divided_value=138, f_action=1)
division_table.add_with_set_division_action(divided_value=139, f_action=1)
division_table.add_with_set_division_action(divided_value=140, f_action=1)
division_table.add_with_set_division_action(divided_value=141, f_action=1)
division_table.add_with_set_division_action(divided_value=142, f_action=1)
division_table.add_with_set_division_action(divided_value=143, f_action=1)
division_table.add_with_set_division_action(divided_value=144, f_action=1)
division_table.add_with_set_division_action(divided_value=145, f_action=1)
division_table.add_with_set_division_action(divided_value=146, f_action=1)
division_table.add_with_set_division_action(divided_value=147, f_action=1)
division_table.add_with_set_division_action(divided_value=148, f_action=1)
division_table.add_with_set_division_action(divided_value=149, f_action=1)
division_table.add_with_set_division_action(divided_value=150, f_action=1)
division_table.add_with_set_division_action(divided_value=151, f_action=1)
division_table.add_with_set_division_action(divided_value=152, f_action=1)
division_table.add_with_set_division_action(divided_value=153, f_action=1)
division_table.add_with_set_division_action(divided_value=154, f_action=1)
division_table.add_with_set_division_action(divided_value=155, f_action=1)
division_table.add_with_set_division_action(divided_value=156, f_action=1)
division_table.add_with_set_division_action(divided_value=157, f_action=1)
division_table.add_with_set_division_action(divided_value=158, f_action=1)
division_table.add_with_set_division_action(divided_value=159, f_action=1)
division_table.add_with_set_division_action(divided_value=160, f_action=1)
division_table.add_with_set_division_action(divided_value=161, f_action=1)
division_table.add_with_set_division_action(divided_value=162, f_action=1)
division_table.add_with_set_division_action(divided_value=163, f_action=1)
division_table.add_with_set_division_action(divided_value=164, f_action=1)
division_table.add_with_set_division_action(divided_value=165, f_action=1)
division_table.add_with_set_division_action(divided_value=166, f_action=1)
division_table.add_with_set_division_action(divided_value=167, f_action=1)
division_table.add_with_set_division_action(divided_value=168, f_action=1)
division_table.add_with_set_division_action(divided_value=169, f_action=1)
division_table.add_with_set_division_action(divided_value=170, f_action=1)
division_table.add_with_set_division_action(divided_value=171, f_action=1)
division_table.add_with_set_division_action(divided_value=172, f_action=1)
division_table.add_with_set_division_action(divided_value=173, f_action=1)
division_table.add_with_set_division_action(divided_value=174, f_action=1)
division_table.add_with_set_division_action(divided_value=175, f_action=1)
division_table.add_with_set_division_action(divided_value=176, f_action=1)
division_table.add_with_set_division_action(divided_value=177, f_action=1)
division_table.add_with_set_division_action(divided_value=178, f_action=1)
division_table.add_with_set_division_action(divided_value=179, f_action=1)
division_table.add_with_set_division_action(divided_value=180, f_action=1)
division_table.add_with_set_division_action(divided_value=181, f_action=1)
division_table.add_with_set_division_action(divided_value=182, f_action=1)
division_table.add_with_set_division_action(divided_value=183, f_action=1)
division_table.add_with_set_division_action(divided_value=184, f_action=1)
division_table.add_with_set_division_action(divided_value=185, f_action=1)
division_table.add_with_set_division_action(divided_value=186, f_action=1)
division_table.add_with_set_division_action(divided_value=187, f_action=1)
division_table.add_with_set_division_action(divided_value=188, f_action=1)
division_table.add_with_set_division_action(divided_value=189, f_action=1)
division_table.add_with_set_division_action(divided_value=190, f_action=1)
division_table.add_with_set_division_action(divided_value=191, f_action=1)
division_table.add_with_set_division_action(divided_value=192, f_action=1)
division_table.add_with_set_division_action(divided_value=193, f_action=1)
division_table.add_with_set_division_action(divided_value=194, f_action=1)
division_table.add_with_set_division_action(divided_value=195, f_action=1)
division_table.add_with_set_division_action(divided_value=196, f_action=1)
division_table.add_with_set_division_action(divided_value=197, f_action=1)
division_table.add_with_set_division_action(divided_value=198, f_action=1)
division_table.add_with_set_division_action(divided_value=199, f_action=1)
division_table.add_with_set_division_action(divided_value=200, f_action=1)
division_table.add_with_set_division_action(divided_value=201, f_action=1)
division_table.add_with_set_division_action(divided_value=202, f_action=1)
division_table.add_with_set_division_action(divided_value=203, f_action=1)
division_table.add_with_set_division_action(divided_value=204, f_action=1)
division_table.add_with_set_division_action(divided_value=205, f_action=1)
division_table.add_with_set_division_action(divided_value=206, f_action=1)
division_table.add_with_set_division_action(divided_value=207, f_action=1)
division_table.add_with_set_division_action(divided_value=208, f_action=1)
division_table.add_with_set_division_action(divided_value=209, f_action=1)
division_table.add_with_set_division_action(divided_value=210, f_action=1)
division_table.add_with_set_division_action(divided_value=211, f_action=1)
division_table.add_with_set_division_action(divided_value=212, f_action=1)
division_table.add_with_set_division_action(divided_value=213, f_action=1)
division_table.add_with_set_division_action(divided_value=214, f_action=1)
division_table.add_with_set_division_action(divided_value=215, f_action=1)
division_table.add_with_set_division_action(divided_value=216, f_action=1)
division_table.add_with_set_division_action(divided_value=217, f_action=1)
division_table.add_with_set_division_action(divided_value=218, f_action=1)
division_table.add_with_set_division_action(divided_value=219, f_action=1)
division_table.add_with_set_division_action(divided_value=220, f_action=1)
division_table.add_with_set_division_action(divided_value=221, f_action=1)
division_table.add_with_set_division_action(divided_value=222, f_action=1)
division_table.add_with_set_division_action(divided_value=223, f_action=1)
division_table.add_with_set_division_action(divided_value=224, f_action=1)
division_table.add_with_set_division_action(divided_value=225, f_action=1)
division_table.add_with_set_division_action(divided_value=226, f_action=1)
division_table.add_with_set_division_action(divided_value=227, f_action=1)
division_table.add_with_set_division_action(divided_value=228, f_action=1)
division_table.add_with_set_division_action(divided_value=229, f_action=1)
division_table.add_with_set_division_action(divided_value=230, f_action=1)
division_table.add_with_set_division_action(divided_value=231, f_action=1)
division_table.add_with_set_division_action(divided_value=232, f_action=1)
division_table.add_with_set_division_action(divided_value=233, f_action=1)
division_table.add_with_set_division_action(divided_value=234, f_action=1)
division_table.add_with_set_division_action(divided_value=235, f_action=1)
division_table.add_with_set_division_action(divided_value=236, f_action=1)
division_table.add_with_set_division_action(divided_value=237, f_action=1)
division_table.add_with_set_division_action(divided_value=238, f_action=1)
division_table.add_with_set_division_action(divided_value=239, f_action=1)
division_table.add_with_set_division_action(divided_value=240, f_action=1)
division_table.add_with_set_division_action(divided_value=241, f_action=1)
division_table.add_with_set_division_action(divided_value=242, f_action=1)
division_table.add_with_set_division_action(divided_value=243, f_action=1)
division_table.add_with_set_division_action(divided_value=244, f_action=1)
division_table.add_with_set_division_action(divided_value=245, f_action=1)
division_table.add_with_set_division_action(divided_value=246, f_action=1)
division_table.add_with_set_division_action(divided_value=247, f_action=1)
division_table.add_with_set_division_action(divided_value=248, f_action=1)
division_table.add_with_set_division_action(divided_value=249, f_action=1)
division_table.add_with_set_division_action(divided_value=250, f_action=1)
division_table.add_with_set_division_action(divided_value=251, f_action=1)
division_table.add_with_set_division_action(divided_value=252, f_action=1)
division_table.add_with_set_division_action(divided_value=253, f_action=1)
division_table.add_with_set_division_action(divided_value=254, f_action=1)
division_table.add_with_set_division_action(divided_value=255, f_action=1)
bfrt.complete_operations()

print("******************* SAMPLE PROGAMMING RESULTS *****************")
